### ISSUE TITLE
YouTube requires HTTPS, module should always use that instead of current protocol

### ISSUE THREAD

**Issue by teppokoivula** [ryancramerdesign/TextformatterVideoEmbed#16]
Hey @ryancramerdesign,

This module currently uses the protocol from local site, while YouTube seems to no longer accept HTTP requests. Unless you can see a problem with that, this:

```
			$oembedURL = 
				"$this->http://www.youtube.com/oembed?url=" . urlencode($matches[1][$key]) . 
				"&format=json&maxwidth={$this->maxWidth}&maxheight={$this->maxHeight}";
```

... should be changed to:

```
			$oembedURL = 
				"https://www.youtube.com/oembed?url=" . urlencode($matches[1][$key]) . 
				"&format=json&maxwidth={$this->maxWidth}&maxheight={$this->maxHeight}";
```

Thanks for considering!

**Comment by teppokoivula** [comment]
Related: https://processwire.com/talk/topic/1536-module-video-embed-for-youtubevimeo-textformattervideoembed/?do=findComment&comment=210117

**Comment by adrianbj** [comment]
@ryancramerdesign - not sure if some even more recent changes were made to youtube' oembed, but I found I had to do this:

```
$video_id = $matches[2][$key];
$oembedURL =
	"https://youtube.com/oembed?url=https://www.youtube.com/watch?v=" . $video_id .
	"&format=json&maxwidth={$this->maxWidth}&maxheight={$this->maxHeight}";
```

so that I built the url query string up that way specifically because the link that was embedded was this older format:
https://www.youtube.com/v/Pud1sv7obRk

**Comment by teppokoivula** [comment]
@ryancramerdesign, just noting that this is still an issue. Should be a pretty simple fix — there's no obvious reason why HTTP should ever be preferred over HTTPS here, especially now that YouTube no longer responds to HTTP requests. Thanks! :)

**Comment by teppokoivula** [comment]
This has been fixed on 2.x versions of the module.
