### ISSUE TITLE
Error: Exception: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value

### ISSUE THREAD

**Issue by chriswthomson** [ryancramerdesign/TextformatterVideoEmbed#21]
Trying to embed

https://www.youtube.com/watch?v=W2omjkNmse4

Throws this error:

Error: Exception: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xCC\x88dens...' for column `db`.`textformatter_video_embed`.`embed_code` at row 1 (in WireDatabasePDOStatement.php line 168)

#0 WireDatabasePDOStatement.php (168): PDOStatement->execute(NULL)
#1 WireDatabasePDOStatement.php (148): WireDatabasePDOStatement->executeDebug(NULL)
#2 site/modules/TextformatterVideoEmbed/TextformatterVideoEmbed.module (306): WireDatabasePDOStatement->execute()
#3 site/modules/TextformatterVideoEmbed/TextformatterVideoEmbed.module (235): TextformatterVideoEmbed->getNewEmbedCode('https://www.you...', 'w2omjknmse4', 'https://www.you/...', true)
#4 site/modules/TextformatterVideoEmbed/TextformatterVideoEmbed.module (472): TextformatterVideoEmbed->getEmbedCode('https://www.you...', 'w2omjknmse4', 'ht

This appears to be caused by the ö in the video title.

Can this be remedied? This is on version 2.0.2.

**Comment by iamwebrocker** [comment]
I just embedded the video url on my site as a test -- it works fine.

<img width="725" alt="grafik" src="https://user-images.githubusercontent.com/1223080/196058404-3d478e48-ccc7-4032-9818-f9664515da82.png">

<img width="909" alt="grafik" src="https://user-images.githubusercontent.com/1223080/196058390-81afcee1-f9bc-425f-9166-6ab9e8e6d9ac.png">

Tested on ProcessWire 3.0.200 and VideoEmbed 2.0.2

**Comment by chriswthomson** [comment]
Hi @iamwebrocker,

Thanks - just tested this on a more recent site and had no issues, this issue occurred on an older site I'd just upgraded from 2.8 to 3. I suspect database collation. I'll investigate further and will likely close if I can resolve easily.

Cheers,

Chris

**Comment by chriswthomson** [comment]
Yep the collation for the module's table was being set automatically as latin1_swedish_ci. I changed this to utf8_general_ci and that has resolved the issue.
